fix(@clayui/css): Improving focus blue line contrast
liferay/clay pull request #5440
Opened 2023-03-27 09:06 UTC by marcoscv-work

fix for:
https://github.com/liferay/clay/issues/5439

2023-03-27 22:03 UTC, pat270 requested changes
Is this only for thin focus outlines or is it across the board? If it's across the board we should probably change the values in
```
$component-focus-box-shadow
$component-focus-inset-box-shadow
$cadmin-component-focus-box-shadow
$cadmin-component-focus-inset-box-shadow
```

2023-03-28 18:39 UTC, marcoscv-work commented
yeah, across the board, feel free to make the change! thanks @pat270

2023-03-29 22:50 UTC, pat270 approved these changes

2023-03-30 18:22 UTC, matuzalemsteles approved these changes

2023-03-30 18:22 UTC, merged