feat(@clayui/css): Add new twitter-x icon
liferay/clay pull request #5719
Opened 2023-11-14 17:24 UTC by ilzamcmed

Jira issue: https://liferay.atlassian.net/browse/LPS-201731

2023-11-16 13:48 UTC, ilzamcmed commented
This PR is ready for review. :tada: 
@pat270 @ethib137

2023-11-16 19:53 UTC, pat270 requested changes

2023-11-16 19:53 UTC, pat270 commented on packages/clay-css/src/images/icons/twitter-x.svg
> +<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
We need to replace `width` and `height` with `viewBox="0 0 16 16"`.

2023-11-16 19:53 UTC, pat270 commented on packages/clay-css/src/images/icons/twitter-x.svg
> +    <g clip-path="url(#Icon-twitter-x__a)">
We need to change the indent from spaces to tab.

2023-11-16 21:47 UTC, pat270 commented
One other note, we shouldn't merge this until we finish https://liferay.atlassian.net/browse/LPS-199577. The viewBox="0 0 16 16" will cause https://liferay.atlassian.net/browse/LPS-201063.

2023-11-17 22:35 UTC, pat270 commented
@ilzamcmed I removed the attribute `fill="#000"` from `packages/clay-css/src/images/icons/twitter-x.svg` and added the license text.

2023-11-17 22:35 UTC, pat270 approved these changes

2023-11-17 22:53 UTC, merged