docs(@icons): Change icons resolution to 16px
liferay/clay pull request #5741
Opened 2023-12-14 17:55 UTC by ilzamcmed

Jira issue: https://liferay.atlassian.net/browse/LPS-201961

2023-12-14 20:24 UTC, ilzamcmed commented
Hey @pat270 , this PR is ready for review
Thanks!

2023-12-14 20:57 UTC, ilzamcmed commented on packages/clay-css/src/images/icons/Union 5.svg
> +<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path class="lexicon-icon-outline" d="m11.647.365 4.037 4.031c.875 1.019-.23 2.375-1.353 1.785l-.987 1.975-5.625-5.438L9.83 1.674C9.25.64 1
Waiting confirmation on how this icon should be called

2023-12-14 20:58 UTC, ilzamcmed commented on packages/clay-css/src/images/icons/Vector 1.svg
> +-->
Waiting confirmation on how this icon should be called

2023-12-14 22:47 UTC, pat270 commented
@ilzamcmed it looks pretty good! The only change we need is to remove `fill="#000"` from many of the icons. It doesn't inherit color changes.

![Screen Shot 2023-12-14 at 2 44 42 PM](https://github.com/liferay/clay/assets/788266/ac88c0e1-a158-4eed-a1a3-8f8a13b6d586)

All the icons should be blue not black.

2023-12-14 22:49 UTC, pat270 requested changes
Need to remove `fill="#000"`

2023-12-15 17:49 UTC, ilzamcmed commented
Thanks @pat270 
I believe everything is ok now. The only question I have is related to the icons called `Union` (didn't find any related one) and `Vector` (this one is similar to the geolocation icon but a bit small).

2023-12-18 17:58 UTC, pat270 requested changes
@emiliano-cicero There were some icons not included in the zip. These icons are still `viewBox="0 0 512 512"`. Are we deleting them? If we do, there will be complications and we will probably have to provide backward compatibility.

```
add-role.svg
align-right.svg
anonymize.svg
arrow-right-full.svg
arrow-up-full.svg
automatic-translate.svg
bell-full.svg
bolt.svg
change-list-disabled.svg
comments.svg
custom-field.svg
desktop.svg
devices.svg
diagonal-line.svg
embed.svg
environment-connected.svg
environment-disconnected.svg
environment.svg
geolocation.svg
import-export.svg
info-panel-closed.svg
lock-dots.svg
megaphone-full.svg
minus-circle.svg
order-arrow.svg
order-form-pencil.svg
order-list-down.svg
order-list-up.svg
pages-tree.svg
pin-full.svg
product-menu.svg
rectangle.svg
relationship.svg
remove-role.svg
reset.svg
share-alt.svg
sign-in.svg
social-twitter.svg
sticky.svg
textbox.svg
third-party.svg
twitter-x.svg
unpin.svg
upload-multiple.svg
urgent.svg
warning-full.svg
```

2023-12-18 19:07 UTC, pat270 commented
@ilzamcmed we can rename the two icons

```
union 5 => unpin.svg
vector 1 => geolocation.svg
```

2023-12-18 19:13 UTC, ilzamcmed commented
> @emiliano-cicero There were some icons not included in the zip. These icons are still `viewBox="0 0 512 512"`. Are we deleting them? If we do, there will be complications and we will probably have to provide backward compatibility.
> 
> ```
> add-role.svg
> align-right.svg
> anonymize.svg
> arrow-right-full.svg
> arrow-up-full.svg
> automatic-translate.svg
> bell-full.svg
> bolt.svg
> change-list-disabled.svg
> comments.svg
> custom-field.svg
> desktop.svg
> devices.svg
> diagonal-line.svg
> embed.svg
> environment-connected.svg
> environment-disconnected.svg
> environment.svg
> geolocation.svg (vector 1.svg)
> import-export.svg
> info-panel-closed.svg
> lock-dots.svg
> megaphone-full.svg
> minus-circle.svg
> order-arrow.svg
> order-form-pencil.svg
> order-list-down.svg
> order-list-up.svg
> pages-tree.svg
> pin-full.svg
> product-menu.svg
> rectangle.svg
> relationship.svg
> remove-role.svg
> reset.svg
> share-alt.svg
> sign-in.svg
> social-twitter.svg
> sticky.svg
> textbox.svg
> third-party.svg
> twitter-x.svg
> unpin.svg (union 5.svg)
> upload-multiple.svg
> urgent.svg
> warning-full.svg
> ```

Should we consider the flags also? They are all `viewBox="0 0 512 512"`

2023-12-18 19:16 UTC, pat270 commented
Yes flags should be converted too.

2023-12-28 18:11 UTC, ilzamcmed commented
Hey @emiliano-cicero , do you have any updates on the icons?
Thanks!

2024-01-12 13:39 UTC, ilzamcmed commented
To be sent in another moment after design icons review

2024-01-12 13:39 UTC, closed without merging