feat(@clayui/css): Add new icons: content-shield, scim, shield-asterisk
liferay/clay pull request #5804
Opened 2024-04-11 16:43 UTC by SelenaAungst

https://liferay.atlassian.net/browse/LPD-21829

2024-04-11 21:02 UTC, pat270 requested changes
Lastly, we should use tabs instead of spaces to indent code.

2024-04-11 21:02 UTC, pat270 commented on packages/clay-css/src/images/icons/content-shield.svg
> +<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
Right now `viewBox="0 0 16 16"` won't work with the `clay-icon` tag in DXP. It's hardcoded to be `viewBox="0 0 512 512"`. We need the `viewBox="0 0 512 512"` version until we can convert everything to `0 0 16 16`.

2024-04-15 18:29 UTC, SelenaAungst commented
Hi @pat270,
I tried changing the viewBox values to 512, should this be manually updated in icons.svg as well or is there a way to update automatically? Additionally, where are there spaces that need to be changed to tabs?
Thanks for reviewing this!

2024-04-15 22:01 UTC, pat270 commented
@SelenaAungst we can't change the viewBox manually here. We need Lexicon to provide us with svg's that are 512 x 512.

2024-04-15 22:02 UTC, pat270 commented on packages/clay-css/src/images/icons/content-shield.svg
> +    <path fill-rule="evenodd" clip-rule="evenodd" d="M0 1.625V11.375C0 12.2713 0.728394 13 1.625 13H7V11.375H1.625V1.625H11.375V6H13V1.625C13 0.728716 12.2716 0 11.375 0H1.625C0.728394 0 0 0.728716 0
@SelenaAungst these indent's are using spaces. It should be tabs. Your code editor should have something that can convert to tabs.

2024-04-15 22:16 UTC, SelenaAungst commented
Thanks for pointing this out! I think I resolved those issues, please let me know if there is anything else I can add/change for this @pat270

2024-04-16 17:24 UTC, pat270 commented
@SelenaAungst I'm getting this

![shield-icons](https://github.com/liferay/clay/assets/788266/f076467c-6d6b-40b5-96aa-923baf000156)

2024-04-16 17:54 UTC, SelenaAungst commented
@pat270 hmm yeah I am not seeing them now either after changing to 512

2024-04-16 19:07 UTC, pat270 commented
@SelenaAungst I was able to change the size export them from Lexicon's Icon Figma Library.

2024-04-16 19:07 UTC, pat270 approved these changes

2024-04-16 19:10 UTC, SelenaAungst commented
Thanks @pat270!

2024-04-16 19:20 UTC, merged